Перемножение матриц
Напишите две функции, каждая из которых перемножает две квадратные матрицы: одна без использования встроенных функций numpy, а другая --- с помощью numpy. На вход первой задаче подаются списки размера size по size элементов в каждом. На вход второй задаче подаются объекты типа np.ndarray --- квадратные матрицы одинакового размера. 

Первая функция должна возвращать список списков, а вторая -- np.array.

In [21]:
import numpy as np

def no_numpy_mult(first, second):
    """
    param first: list of "size" lists, each contains "size" floats
    param first: list of "size" lists, each contains "size" floats
    """
    result = []
    # m*n n*k
    m = len(first)
    k = len(second[0])
    n = len(second)
    
    for mi in range(m):
        ll = []
        for j in range(k):
            ll.append(0)
        result.append(ll)

    for ki in range(k):
        temp = []
        for ni in range(n):
            temp.append(second[ni][ki]) # это вертикальный столбец из второй матрицы
        for mi in range(m): # обходим строки первой матрицы и умножаем на столбец второй
            sum = 0
            for ki2 in range(k):
                sum += temp[ki2]*first[mi][ki2]
            result[mi][ki] = sum # присваиваем по номеру строк 1 матрицы и столбца 2

    return result

no_numpy_mult([[1, 2, 3],[4, 5, 6]],[[11, 22, 33],[44, 55, 66],[77, 88, 99]])

def numpy_mult(first, second):
    """
    param first: np.array[size, size]
    param second: np.array[size, size]
    """

    result = first.dot(second)
    return result

[[330, 396, 462], [726, 891, 1056]]


Вам подаются на вход два вектора a и b в трехмерном пространстве. Реализуйте их скалярное произведение с помощью numpy и без. 

In [0]:
import numpy as np

def no_numpy_scalar(v1, v2):
    #param v1, v2: lists of 3 ints
    sum = 0
    for i in range(len(v1)):
        sum += v1[i]*v2[i]
    result = sum
    return result

def numpy_scalar (v1, v2):
    #param v1, v2: np.arrays[3]

    result = v1.dot(v2)
    return result

Напишите функцию, которая находит сумму четных элементов на главной диагонали квадратной матрицы (именно чётных элементов, а не элементов на чётных позициях!). Если чётных элементов нет, то вывести 0. Используйте библиотеку numpy.

In [24]:
import numpy as np

def diag_2k(a):
    #param a: np.array[size, size]
    diag = np.diagonal(a, offset=0)
    print(diag)
    sum = 0
    for i in diag:
        if i % 2 == 0:
            sum += i

    result = sum
    print(result)
    return result

diag_2k(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

[1 5 9]
9


9

На вход дан двумерный массив XX. Напишите функцию, которая для каждой строчки x = (x_1, x_2, \ldots, x_n)x=(x 1 ​ ,x 2 ​ ,…,x n ​ ) массива XX строит строчку s = (s_1, s_2, \ldots, s_n)s=(s 1 ​ ,s 2 ​ ,…,s n ​ ), где s_k=x_1+...+x_ks k ​ =x 1 ​ +...+x k ​ , а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и XX.

In [12]:
import numpy as np

def cumsum(A):
    #param A: np.array[m,n]
    result = []
    for m in A:
        line = np.cumsum(m[:])
        result.append(line)

    return result

cumsum(np.array([[1,2,3],[4,5,6]]))


[[array([1, 3, 6])], [array([ 4,  9, 15])]]


[[array([1, 3, 6])], [array([ 4,  9, 15])]]

Склеивание Задан двумерный массив XX. Для каждой строчки массива XX необходимо сделать следующее преобразование. Пусть дана строчка xx. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число aa (значение по умолчанию a = 1a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив xx с преобразованным xx и вывести. Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива XX. Массив XX при этом должен остаться без изменений. Используйте библиотеку numpy. Пример: x = [[100, 200, 300, 400, 500100,200,300,400,500]] -> [[100, a, 300, a, 500100,a,300,a,500]] -> [[500^3, a, 300^3, a, 100^3500 3 ,a,300 3 ,a,100 3 ]] -> склеиваем -> [[100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3100,200,300,400,500,500 3 ,a,300 3 ,a,100 3 ]]

In [46]:
import numpy as np

def transform(X, a=1):
    """
    param X: np.array[batch_size, n]
    """
    newX = []
    for x in X:
        B = np.copy(x)
        B[1::2] = a
        B[0::2] = B[0::2]**3
        B = np.flip(B, axis=0)
        Y = np.concatenate((x, B), axis=0)
        newX.append(Y)
    return newX

print(transform(np.array([[100,200,300,400,500]])))

[array([      100,       200,       300,       400,       500, 125000000,
               1,  27000000,         1,   1000000])]


С помощью numpy написать функцию для кодирования массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array([1, 2, 3, 1, 5, 2, 3]), np.array([1, 2, 2, 2, 2, 1, 2]))

In [59]:
import numpy as np

def encode(a):
    X = np.array([])
    Y = np.array([])
    i_0 = None
    count = 0

    for i in a:
        if i != i_0 and i_0 != None:
            X = np.append(X, i_0)
            Y = np.append(Y, count)
            i_0 = i
            count = 1
        else:
            if i_0 is None:
                i_0 = i
            count += 1

    if i == i_0:
        X = np.append(X, i_0)
        Y = np.append(Y, count)

    result = np.array([X,Y])
    return result

print(encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])))

[[1. 2. 3. 1. 5. 2. 3.]
 [1. 2. 2. 2. 2. 1. 2.]]
ERROR! Session/line number was not unique in database. History logging moved to new session 62
